version: 2
jobs:
  setupAmazonLinux:
    docker:
      - image: amazonlinux
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            make
            make setup-amazon-linux-for-python36
            make setup-amazon-linux-for-docker

workflows:
  version: 2
  workflow:
    jobs:
      - setupAmazonLinux
